### PR TITLE
Support arguments to the aws command

### PR DESCRIPTION
**Pull request by gdhbashton**
Hi,

I love your includes - especially for `cf_tail` - however it didn't support profiles in `~/.aws/config`, and I have 20+ profiles for different customers and environments, so I included a trivial method to support this.

It works for me... :)

Cheers,
Gavin.

### CODE REVIEW

**Comment by mbailey** [comment]
Thanks Gavin!

Can you not just set AWS_DEFAULT_PROFILE?

http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment

**Comment by gdhbashton** [comment]
Hey Mike,

Thanks for the suggestion - that would certainly have the immediately desired effect.

When it comes to customer profiles, I'm really disinclined to rely on default behaviour; I know for sure that I will select the wrong tab at some point and do something unpleasant, hence if I have to set the profile on each run. I did also set the var name to AWS_OPTIONS so other options e.g. `region` can be specified - all in the interests of flexibility.

`credulous` looks very interesting. The idea of just running `cred` for each of those accounts seems very attractive, though it delivers the same issue of tab confusion... (entirely my issue, of course...)

Do you feel that this PR is sufficiently valuable to merge?

**Comment by mbailey** [comment]
Do you set the environment variable each time you run the command?

**Comment by gdhbashton** [comment]
Ah ha, yes I do... in which case there's really no difference between setting `AWS_DEFAULT_PROFILE` and `AWS_OPTIONS` for this use-case.

I can imagine that `AWS_OPTIONS` might be useful for setting the region but I can understand if you'd prefer not to merge this PR.

**Comment by mbailey** [comment]
Thanks. I'd prefer to support the environment variables used bu AWSCLI.

**Comment by tomberek** [comment]
An AWS_OPTIONS would be helpful in some other cases as well where other env vars or .aws/config is not supported. eg: https://github.com/aws/aws-cli/issues/1270

**Pull request closed without merging**
