### PR TITLE
Updated instance-functions file

### PR DESCRIPTION
**Pull request by mike-mosher**
- added `instance-public-ip` and `instance-private-ip`

Example:
```
$ instance-public-ip 
USAGE: instance-public-ip instance-id [instance-id]

$ instance-private-ip 
USAGE: instance-private-ip instance-id [instance-id]

$ instance-private-ip i-0123456789abcdefg
172.31.16.190

$ instance-public-ip i-0123456789abcdefg
52.12.29.34
```

### CODE REVIEW

**Comment by mike-mosher** [comment]
Any thoughts or comments on this?

**Comment by mbailey** [comment]
What's your use case? Can you make use of the existing function `instance-ip()`?
```
$ instances | instance-ip
i-01234567890abcdef  172.31.0.2  52.22.42.12
```

**Comment by mike-mosher** [comment]
Many times you want to output just the public or private IP, for example, in order to SSH to these IPs.  It's nice to have a function for this instead of having to pipe the output of `instance-ip` to awk

**Comment by mbailey** [comment]
I appreciate that it would be of value to you and am glad that you were able to create a solution.

In the readme I encourage people to maintain their own fork with extra commands. Sometimes I
will incorporate them into master but even many of my own functions don't make it in! If you keep them
in a separate file your unlikely to ever get merge conflicts. There is so little shared code (that's deliberate) that you're unlikely to ever have them break due to an upstream change.

I'm happy to be convinced otherwise but for now I don't feel they add enough to justify the extra two commands. Happy to discuss if you want further explanation of my reasoning or want to give more detail about yours. 

BTW, does `instance-ssh` work for you?

**Pull request closed without merging**
